export default {
    primary: '#469afc',
    lightPrimary: '#f26df1',
    secondary: '#bd3a3f',
    accent: '#4442b7',
    lightAccent: '#5b94f7',
    brightBlue: '#5260f2',
    cardBackground: '#f8fbff',
    cardBorder: '#e0eeff',
    linkColor: '#5260f2',
    heartColor: '#bd3a3f',
    commentColor: '#d8eafe',
    newCommnetColor: '#f8fbff',
    newCommentBorderColor: '#a5cefe',
    backgroundColor: '#ffffff',
}